### ISSUE TITLE
The different concentrations of ore should use a single color

### ISSUE THREAD

**Issue by cmaes** [EmilienDupont/openPitMining#4]
Right now we use dark gray, gray, red, yellow, and purple to represent the different concentrations of ore in the demo. Could we use a gradient of a single color instead. For example, very light blue, light blue, blue, dark blue.

A chloropath as shown in these two examples might make good colors:
http://bl.ocks.org/mbostock/8ca036b3505121279daf
http://bl.ocks.org/mbostock/5737662

**Comment by EmilienDupont** [comment]
Fixed.
